const fileExtensionsMapping = {
  txt: "plaintext",
  "": "plaintext",
  abap: "abap",
  apex: "apex",
  azcli: "azcli",
  bat: "bat",
  bicep: "bicep",
  cameligo: "cameligo",
  clojure: "clojure",
  coffeescript: "coffeescript",
  c: "c",
  cpp: "cpp",
  csharp: "csharp",
  csp: "csp",
  css: "css",
  cypher: "cypher",
  dart: "dart",
  dockerfile: "dockerfile",
  ecl: "ecl",
  ex: "elixir",
  flow9: "flow9",
  fsharp: "fsharp",
  freemarker2: "freemarker2",
  "freemarker2.tag-angle.interpolation-dollar":
    "freemarker2.tag-angle.interpolation-dollar",
  "freemarker2.tag-bracket.interpolation-dollar":
    "freemarker2.tag-bracket.interpolation-dollar",
  "freemarker2.tag-angle.interpolation-bracket":
    "freemarker2.tag-angle.interpolation-bracket",
  "freemarker2.tag-bracket.interpolation-bracket":
    "freemarker2.tag-bracket.interpolation-bracket",
  "freemarker2.tag-auto.interpolation-dollar":
    "freemarker2.tag-auto.interpolation-dollar",
  "freemarker2.tag-auto.interpolation-bracket":
    "freemarker2.tag-auto.interpolation-bracket",
  go: "go",
  graphql: "graphql",
  handlebars: "handlebars",
  hcl: "hcl",
  html: "html",
  ini: "ini",
  java: "java",
  js: "javascript",
  jl: "julia",
  kt: "kotlin",
  less: "less",
  lexon: "lexon",
  lua: "lua",
  liquid: "liquid",
  m3: "m3",
  md: "markdown",
  mdx: "mdx",
  mips: "mips",
  msdax: "msdax",
  mysql: "mysql",
  m: "objective-c",
  pas: "pascal",
  pascaligo: "pascaligo",
  pl: "perl",
  pgsql: "pgsql",
  php: "php",
  pla: "pla",
  postiats: "postiats",
  powerquery: "powerquery",
  ps1: "powershell",
  proto: "proto",
  pug: "pug",
  py: "python",
  qsharp: "qsharp",
  r: "r",
  cshtml: "razor",
  redis: "redis",
  redshift: "redshift",
  rst: "restructuredtext",
  rb: "ruby",
  rs: "rust",
  sb: "sb",
  scala: "scala",
  scm: "scheme",
  scss: "scss",
  sh: "shell",
  sol: "sol",
  aes: "aes",
  sparql: "sparql",
  sql: "sql",
  st: "st",
  swift: "swift",
  sv: "systemverilog",
  v: "verilog",
  tcl: "tcl",
  twig: "twig",
  ts: "typescript",
  vb: "vb",
  wgsl: "wgsl",
  xml: "xml",
  yaml: "yaml",
  json: "json",
};

export type IFileType = typeof fileExtensionsMapping;

export const fileTypeMap = (fileType: keyof IFileType) => {
  return fileExtensionsMapping[fileType];
};
